"use client";

import Link from "next/link";
import { GitCompareArrows, Loader2, RefreshCw, ShieldCheck, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { compareAnalyses, deleteAnalysis, listAnalyses } from "@/lib/api";
import type { DealComparison, SavedSummary } from "@/lib/types";

const money=(value:number|null)=>value===null?"N/M":`$${value.toFixed(1)}m`;
const multiple=(value:number|null)=>value===null?"N/M":`${value.toFixed(2)}x`;
const riskTone=(recommendation:string):"risk"|"warning"|"positive"=>recommendation==="Decline"?"risk":recommendation.includes("conditions")||recommendation.includes("diligence")?"warning":"positive";

export default function SavedAnalysesPage(){
  const [items,setItems]=useState<SavedSummary[]>([]);
  const [selected,setSelected]=useState<string[]>([]);
  const [comparison,setComparison]=useState<DealComparison|null>(null);
  const [error,setError]=useState("");
  const [loading,setLoading]=useState(true);
  const [comparing,setComparing]=useState(false);
  const load=()=>{setLoading(true);setError("");listAnalyses().then(setItems).catch(e=>setError(e.message)).finally(()=>setLoading(false))};
  useEffect(load,[]);
  const toggle=(id:string)=>{setComparison(null);setSelected(current=>current.includes(id)?current.filter(x=>x!==id):current.length<2?[...current,id]:[current[1],id])};
  const remove=async(id:string)=>{try{await deleteAnalysis(id);setItems(items.filter(x=>x.id!==id));setSelected(selected.filter(x=>x!==id));setComparison(null)}catch(e){setError(e instanceof Error?e.message:"Delete failed")}};
  const compare=async()=>{setComparing(true);setError("");try{setComparison(await compareAnalyses(selected))}catch(e){setError(e instanceof Error?e.message:"Comparison failed")}finally{setComparing(false)}};
  return <main className="mx-auto max-w-[1500px] px-5 py-10 lg:px-8 lg:py-14">
    <div className="mb-9 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="font-mono text-xs uppercase tracking-[.12em] text-accent">Analysis archive</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.045em]">Saved analyses</h1><p className="mt-3 max-w-3xl text-sm leading-relaxed text-ink/60">Reopen an exact calculation snapshot, review its decision record, or select two structures for a backend-generated safety comparison.</p></div><Button variant="outline" onClick={load}><RefreshCw className="h-4 w-4"/>Refresh</Button></div>
    {error&&<div role="alert" className="mb-5 border border-risk/40 bg-risk/5 p-4 text-sm text-risk"><strong>Unable to complete the request.</strong><span className="mt-1 block">{error}</span></div>}
    {selected.length>0&&<section className="mb-8 flex flex-col justify-between gap-4 border border-ink/20 bg-white p-5 sm:flex-row sm:items-center"><div><p className="font-semibold">{selected.length} of 2 structures selected</p><p className="mt-1 text-sm text-ink/55">Select two saved cases for the same borrower. All comparison metrics are returned by Python.</p></div><Button disabled={selected.length!==2||comparing} onClick={compare}>{comparing?<Loader2 className="h-4 w-4 animate-spin"/>:<GitCompareArrows className="h-4 w-4"/>}Compare structures</Button></section>}
    {comparison&&<section className="mb-9 border border-accent/35 bg-white"><div className="flex flex-col justify-between gap-4 border-b border-ink/15 bg-accent/5 p-5 sm:flex-row sm:items-center"><div><p className="font-mono text-[9px] uppercase tracking-wider text-accent">Deterministic safer-structure selection</p><h2 className="mt-2 flex items-center gap-2 text-xl font-semibold"><ShieldCheck className="h-5 w-5 text-accent"/>{comparison.safer_structure_name}</h2></div><div className="max-w-2xl text-sm text-ink/65">{comparison.rationale.join(" ")}</div></div><div className="overflow-x-auto"><table className="data-table min-w-[1180px]"><thead><tr><th>Structure</th><th>Decision</th><th>Grade</th><th>Gross lev.</th><th>Net lev.</th><th>Coverage</th><th>DSCR</th><th>Liquidity</th><th>Total debt</th><th>Sponsor equity</th><th>WA cash rate</th><th>First breach</th><th>Covenants P/F</th><th>Safety score</th></tr></thead><tbody>{comparison.entries.map(entry=><tr key={entry.analysis_id} className={entry.analysis_id===comparison.safer_analysis_id?"bg-accent/10":""}><td><span className="font-semibold">{entry.structure_name}</span>{entry.analysis_id===comparison.safer_analysis_id&&<Badge tone="positive" className="ml-2">Safer</Badge>}</td><td><Badge tone={riskTone(entry.recommendation)}>{entry.recommendation}</Badge></td><td>{entry.risk_grade}</td><td>{multiple(entry.gross_leverage)}</td><td>{multiple(entry.net_leverage)}</td><td>{multiple(entry.interest_coverage)}</td><td>{multiple(entry.dscr)}</td><td>{money(entry.minimum_liquidity)}</td><td>{money(entry.total_debt)}</td><td>{money(entry.sponsor_equity)}</td><td>{entry.weighted_average_cash_interest_rate===null?"N/M":`${(entry.weighted_average_cash_interest_rate*100).toFixed(2)}%`}</td><td>{entry.first_breach_period??"None"}</td><td>{entry.covenant_pass_count}/{entry.covenant_fail_count}</td><td className="font-semibold">{entry.safety_score.toFixed(1)}</td></tr>)}</tbody></table></div><details className="border-t border-ink/15 p-5"><summary className="cursor-pointer font-semibold text-accent">How the safety score works</summary><ul className="mt-3 space-y-2 text-sm text-ink/65">{comparison.methodology.map(item=><li key={item}>• {item}</li>)}</ul></details></section>}
    {loading?<div className="space-y-2" aria-label="Loading saved analyses">{[0,1,2].map(i=><div key={i} className="h-14 animate-pulse border border-ink/15 bg-white"/>)}</div>:items.length===0?<div className="border border-ink/20 bg-white p-8 sm:p-10"><div className="mx-auto max-w-2xl text-center"><span className="font-mono text-[9px] font-semibold uppercase tracking-wider text-accent">Workspace ready</span><GitCompareArrows className="mx-auto mt-5 h-7 w-7 text-ink/35"/><h2 className="mt-5 text-xl font-semibold">Build your analysis archive</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-relaxed text-ink/55">Saved cases appear here with their recommendation, risk grade, first-breach period, and exact deal inputs. Start from a borrower file, save a base case, then duplicate the structure to compare financing alternatives.</p><div className="mt-6 flex flex-wrap justify-center gap-5"><Link href="/borrowers" className="border-b border-accent pb-1 text-sm font-semibold text-accent">Open borrower files</Link><Link href="/demos" className="border-b border-ink/30 pb-1 text-sm font-semibold">Review guided workflows</Link></div></div><div className="mx-auto mt-8 grid max-w-3xl gap-px border border-ink/15 bg-ink/15 text-left sm:grid-cols-3"><div className="bg-paper p-4"><p className="font-mono text-[9px] uppercase tracking-wider text-ink/45">01 · Analyze</p><p className="mt-2 text-sm font-semibold">Select a borrower file</p></div><div className="bg-paper p-4"><p className="font-mono text-[9px] uppercase tracking-wider text-ink/45">02 · Save</p><p className="mt-2 text-sm font-semibold">Store a decision snapshot</p></div><div className="bg-paper p-4"><p className="font-mono text-[9px] uppercase tracking-wider text-ink/45">03 · Compare</p><p className="mt-2 text-sm font-semibold">Evaluate deal structures</p></div></div></div>:<div className="overflow-x-auto border border-ink/20"><table className="data-table"><thead><tr><th>Compare</th><th>Analysis</th><th>Borrower</th><th>Created</th><th>Recommendation</th><th>Grade</th><th>First breach</th><th>Actions</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><input aria-label={`Compare ${item.analysis_name}`} type="checkbox" checked={selected.includes(item.id)} onChange={()=>toggle(item.id)}/></td><td><Link className="font-semibold text-accent hover:underline" href={`/analysis/${item.borrower_id}?saved=${item.id}`}>{item.analysis_name}</Link></td><td>{item.borrower_id}</td><td>{new Date(item.created_at).toLocaleString()}</td><td><Badge tone={riskTone(item.latest_recommendation)}>{item.latest_recommendation}</Badge></td><td>{item.risk_grade}</td><td>{item.first_breach_period??"None"}</td><td><button aria-label={`Delete ${item.analysis_name}`} onClick={()=>remove(item.id)} className="text-risk hover:underline"><Trash2 className="h-4 w-4"/></button></td></tr>)}</tbody></table></div>}
  </main>;
}
